build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.13
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: unit
  commands: make test-unit
  container:
    from: src
- as: e2e-integration
  commands: make test-e2e
  openshift_installer_src:
    cluster_profile: aws
zz_generated_metadata:
  branch: master
  org: devfile
  repo: integration-tests
