base_images:
  cli:
    name: "4.5"
    namespace: ocp
    tag: cli
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.13
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: e2e-integration
  steps:
    cluster_profile: aws
    test:
    - as: devfile-integration-e2e
      commands: oc adm policy add-role-to-user --help
      from: cli
      resources:
        requests:
          cpu: 100m
          memory: 200Mi
    workflow: ipi-aws
zz_generated_metadata:
  branch: master
  org: devfile
  repo: integration-tests
