build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.13
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: e2e-integration
  steps:
    cluster_profile: aws
    test:
    - as: devworkspaces-operator-e2e
      commands: |
        export PATH=$PATH:/tmp/bin
        mkdir /tmp/bin
        curl https://mirror.openshift.com/pub/openshift-v4/clients/oc/4.5/linux/oc.tar.gz | tar xvzf - -C /tmp/bin/ oc
        chmod ug+x /tmp/bin/oc
        /bin/bash .ci/openshift_e2e.sh
      dependencies:
      - env: DEVWORKSPACE_OPERATOR
        name: devworkspace-operator
      from: src
      resources:
        requests:
          cpu: 100m
          memory: 200Mi
    workflow: ipi-aws
zz_generated_metadata:
  branch: master
  org: devfile
  repo: integration-tests
